# Generated by Django 5.2.1 on 2025-06-03 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'избранное',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательно, не более 200 символов', max_length=200, verbose_name='Название')),
                ('measurment', models.CharField(help_text='Обязательно, укажите единицу измерения', max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное, не более 200 символов', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(help_text='Обязательно, добавьте изображение рецепта', upload_to='recipes/images', verbose_name='')),
                ('text', models.TextField(help_text='Обязательно, опишите последовательность приготовления', verbose_name='Описание')),
                ('time_cooking', models.IntegerField(help_text='Обязательно, укажите время в минутах', validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(15)], verbose_name='Время приготовления')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientsRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(1000)])),
            ],
            options={
                'verbose_name': 'связь рецептов и ингридиентов',
                'verbose_name_plural': 'связи рецептов и ингридиентов',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'покупки',
                'verbose_name_plural': 'покупки',
            },
        ),
    ]
