# Generated by Django 5.2.1 on 2025-06-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_cooking',
            new_name='cooking_time',
        ),
    ]
