# Generated by Django 5.2.1 on 2025-06-03 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurment',
            new_name='measurement',
        ),
        migrations.AlterField(
            model_name='recipeingredientsrelated',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
