# Generated by Django 5.2.1 on 2025-06-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user', verbose_name='Автор')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'constraints': [models.UniqueConstraint(fields=('subscription', 'following'), name='unique_name_following')],
            },
        ),
    ]
